account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_page, name='login_page'),
    path('forgot_password/', views.forgot_password_page, name='forgot_password_page'),
    path('create/', views.create_account_page, name='create_account_page'),
    path('home/', views.account_home_page, name='account_home'),
    path('profile/<int:user_id>/', views.account_profile_page, name='account_profile'),
    path('settings/', views.account_settings_page, name='account_settings'),
    path('settings/interests/', views.account_interest, name='personal_interests'),

    re_path(r'^search/(?P<name>[-\S\w\s]+)/$', views.account_search_page, name='search_page'),
]

bands/urls.py
from django.urls import path, re_path
from . import views

app_name = 'bands'

urlpatterns = [
    path('search/all/', views.band_search_page, name='search_page'),
    path('page/<int:band_id>/', views.band_page, name='band_page'),
    # Account band pages
    path('account/search/all/', views.account_band_search_page, name='account_search_page'),
    path('account/create-page/', views.account_create_band_page, name='band_create_page'),
    path('account/page/<int:band_id>/', views.account_band_page, name='account_band_page'),
    path('account/edit-page/<int:band_id>/', views.account_band_edit_page, name='band_edit_page'),
    path('account/admins/<int:band_id>/', views.account_band_admins_page, name='band_admin_page'),
]

contact_us/urls.py
from django.urls import path
from . import views

app_name = "contact_us"

urlpatterns = [
    path('', views.help_page, name='help'),
    path('success/', views.help_email_success, name='success'),
    path('account/', views.help_page_account, name='help_account'),
    path('account/success/', views.help_email_success_account, name='account_success'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('help/', views.help_page, name='help_page'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('band/', include('bands.urls', namespace='bands')),
    path('news/', include('news.urls', namespace='news')),
    path('contact/', include('contact_us.urls', namespace='contact')),
    # path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

home/forms.py
from django import forms

home/views.py
from django.contrib.sessions.models import Session
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from random import choice

from bands.models import Band


def get_user(email):
    try:
        return User.objects.get(email=email.lower())
    except User.DoesNotExist:
        return None


def home_page(request):
    try:
        session_key = request.COOKIES['sessionid']
        session = Session.objects.get(session_key=session_key)
        uid = session.get_decoded().get('_auth_user_id')
        user = User.objects.get(pk=uid)
        return redirect("/account/home/")
    except:
        pass

    bands = Band.objects.all()
    bands_list = []

    while len(bands_list) < 5:
        band = choice(bands)
        if band in bands_list:
            pass
        else:
            if band.band_picture:
                bands_list.append(band)
            else:
                pass

    content = {
        "home": "home",
        "title": "Demontaža",
        "bands_list": bands_list,
    }
    return render(request, "home/home_page.html", content)


def help_page(request):
    try:
        session_key = request.COOKIES['sessionid']
        session = Session.objects.get(session_key=session_key)
        uid = session.get_decoded().get('_auth_user_id')
        user = User.objects.get(pk=uid)
        return redirect("/account/home/")
    except:
        pass

    content = {
        "help_page": "help_page",
        "title": "Pomoć"
    }
    return render(request, "home/help_page.html", content)

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" href="/static/image_&_video/mali.png">

    <!-- Styles & Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'scripts/jquery.min.js' %}"></script>
    <script src="{% static 'scripts/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'scripts/popper.min.js' %}"></script>
    <script src="{% static 'scripts/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!-- Font awesome icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <title>{% block title %}{{ title }}{% endblock %}</title>

</head>
<body onload="fadeInFunction()">
<div style="display:none;" id="myDiv" class="animate-bottom">
    {% include "navbar.html" %}
    {% block content %}

    {% endblock %}
</div>
<script>
    var myVar;

    function fadeInFunction() {
        myVar = setTimeout(showPage, 400);
    }

    function showPage() {
        document.getElementById("myDiv").style.display = "block";
    }
</script>
</body>
</html>

home/templates/navbar.html
{% load thumbnail %}

<!-- Modals -->
<div class="modal fade" id="logout">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="padding:10px;">

            <!-- Modal Header -->
            <div class="modal-header">
                <h5 class="modal-title"><i class="fas fa-sign-out-alt fa-lg"></i>&nbsp;&nbsp;Odjavi se</h5>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="text-justify">
                    <h6 class="text-center">Da li ste sigurni da želite da se odjavite?</h6>
                </div>
            </div>

            <form method="post" action="." name="logout"> {% csrf_token %}
            <!-- Modal footer -->
            <div class="modal-footer">
                <span class="mr-auto">
                    <button type="button"
                            class="btn"
                            data-dismiss="modal"
                            id="ne">Ne</button>
                </span>
                <button type="submit"
                        name="logout"
                        class="btn"
                        id="da">Da
                </button>
            </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="userPages">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content frame">

            <!-- Modal Header -->
            <div class="modal-header">
                <h5 class="modal-title"><i class="fas fa-book-reader"></i>&nbsp;&nbsp;Vaše strane:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="text-justify">
                    {% if user_pages %}
                    {% for page in user_pages %}
                    <div class="link">
                        <a class="modal-user-list" href="{% if page.genre %}{% url 'bands:account_band_page' page.id %}{% endif %}">
                            <div style="display:flex;">
                                {% if page.logo %}
                                <img src="{{ page.logo.url }}" class="avatar-like">&nbsp;
                                {% else %}
                                <h6><i class="fas fa-user-circle fa-2x"></i></h6>&nbsp;
                                {% endif %}
                                <p>{{ page.name }}</p>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p>Nemate vaših kreiranih strana. Takođe niste administrator ni na jednoj od stranica.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="friendRequests">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content frame">

            <!-- Modal Header -->
            <div class="modal-header">
                <h5 class="modal-title"><i class="fas fa-hands-helping"></i>&nbsp;&nbsp;Zahtevi za prijateljstvo:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="text-justify" id="friend_request_list">
                    {% if friend_requests %}
                    {% for friend in friend_requests %}
                    <div style="display:flex;">
                        <a href="{% url 'account:account_profile' friend.id %}">
                            {% if friend.profile.picture %}
                            <img class="avatar-like" src="{% thumbnail friend.profile.picture 150x0 %}">
                            {% else %}
                            <h6><i class="fas fa-user-circle fa-2x"></i></h6>
                            {% endif %}
                        </a>
                        <div>
                            <a href="{% url 'account:account_profile' friend.id %}">
                                <h6 style="margin:6px 0 0 5px;">{{ friend.first_name }} {{ friend.last_name }}</h6>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p>Nemate novih zahteva za prijateljstvo.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End of Modals -->
<!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark">
    <a class="navbar-brand" href="{% if account %}/account/home/{% else %}/{% endif %}"><img src="/static/image_&_video/mali.png" height="50" width="50" alt="demontaza"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if account %}
        <form class="form-inline mr-auto" method="post" action="."> {% csrf_token %}
            <input class="form-control" type="search" placeholder="&#x1F50D;&nbsp;&nbsp;Pretraži" aria-label="Search" name="site_search" style="border-radius:0; width:100%;">
        </form>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if account_home %}active{% endif %}" title="Početna">
                <a class="nav-link" href="{% url 'account:account_home' %}"><i class="fas fa-home fa-lg"></i><span class="link-text">&nbsp;&nbsp;Početna</span></a>
            </li>
            <li class="nav-item dropdown {% if account_profile %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if profile.picture %}<img class="avatar" src="{% thumbnail profile.picture 150x0 %}">{% else %}<i class="fas fa-user fa-lg"></i>{% endif %} {{ user.first_name }}
                </a>
                <div class="dropdown-menu" id="{% if account_profile %}active{% else %}passive{% endif %}" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'bands:band_create_page' %}"><i class="fas fa-plus"></i> Kreiraj stranicu</a>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#userPages"><i class="fas fa-book-reader"></i> Vaše strane</a>
                    <div class="dropdown-divider"></div>
                    <span style="font-weight: 600; color: #a6111a;">Vaš nalog</span>
                    <a class="dropdown-item" href="{% url 'account:account_profile' user.id %}"><i class="fas fa-user"></i> Profil</a>
                    <a class="dropdown-item" href="{% url 'account:account_settings' %}"><i class="fas fa-cog"></i> Podešavanje</a>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logout">
                        <i class="fas fa-sign-out-alt"></i> Odjavi se
                    </a>
                </div>
            </li>
            <li class="nav-item" title="Zahtevi za prijateljstvo" id="fr_req">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#friendRequests"><i class="fas fa-hands-helping fa-lg"></i><span class="link-text">&nbsp;&nbsp;Zahtevi za prijateljstvo</span> {% if friend_requests %}<span class="blink">{{ friend_requests|length }}</span>{% endif %}</a>
            </li>
            <li class="nav-item {% if band_search %}active{% endif %}" title="Spisak svih bendova">
                <a class="nav-link" href="/band/account/search/all/"><i class="fas fa-guitar fa-lg"></i><span class="link-text">&nbsp;&nbsp;Spisak svih bendova</span></a>
            </li>
            <li class="nav-item {% if help_page %}active{% endif %}" title="Pomoć">
                <a class="nav-link" href="{% url 'contact_us:help_account' %}"><i class="fas fa-info-circle fa-lg"></i><span class="link-text">&nbsp;&nbsp;Pomoć</span></a>
            </li>
            <!--
            <li class="nav-item {% if news %}active{% endif %}" title="Demoliranje">
                <a class="nav-link" href="#"><i class="fas fa-hammer fa-lg"></i><span class="link-text">&nbsp;&nbsp;Demoliranje</span></a>
            </li>
            -->
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if login_page %}active{% endif %}" title="Uloguj se">
                <a class="nav-link" href="{% url 'account:login_page' %}"><i class="fas fa-sign-in-alt fa-lg"></i><span class="link-text">&nbsp;&nbsp;Uloguj se</span></a>
            </li>
            <li class="nav-item {% if account_page %}active{% endif %}" title="Kreiraj nalog">
                <a class="nav-link" href="{% url 'account:create_account_page' %}"><i class="fas fa-user-plus fa-lg"></i><span class="link-text">&nbsp;Kreiraj nalog</span></a>
            </li>
            <li class="nav-item {% if band_search %}active{% endif %}" title="Spisak svih bendova">
                <a class="nav-link" href="/band/search/all/"><i class="fas fa-guitar fa-lg"></i><span class="link-text">&nbsp;&nbsp;Spisak svih bendova</span></a>
            </li>
            <li class="nav-item {% if help_page %}active{% endif %}" title="Pomoć">
                <a class="nav-link" href="{% url 'contact:help' %}"><i class="fas fa-info-circle fa-lg"></i><span class="link-text">&nbsp;&nbsp;Pomoć</span></a>
            </li>
            <!--
            <li class="nav-item {% if demoliranje %}active{% endif %}" title="Demoliranje">
                <a class="nav-link" href="{% url 'home:help_page' %}"><i class="fas fa-hammer fa-lg"></i><span class="link-text">&nbsp;&nbsp;Demoliranje</span></a>
            </li>
            -->
        </ul>
        {% endif %}
    </div>
</nav>