account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_page, name='login_page'),
    path('forgot_password/', views.forgot_password_page, name='forgot_password_page'),
    path('create/', views.create_account_page, name='create_account_page'),
    path('home/', views.account_home_page, name='account_home'),
    path('profile/<int:user_id>/', views.account_profile_page, name='account_profile'),
    path('settings/', views.account_settings_page, name='account_settings'),
    path('settings/interests/', views.account_interest, name='personal_interests'),

    re_path(r'^search/(?P<name>[-\S\w\s]+)/$', views.account_search_page, name='search_page'),
]

bands/urls.py
from django.urls import path, re_path
from . import views

app_name = 'bands'

urlpatterns = [
    path('search/all/', views.band_search_page, name='search_page'),
    path('page/<int:band_id>/', views.band_page, name='band_page'),
    # Account band pages
    path('account/search/all/', views.account_band_search_page, name='account_search_page'),
    path('account/create-page/', views.account_create_band_page, name='band_create_page'),
    path('account/page/<int:band_id>/', views.account_band_page, name='account_band_page'),
    path('account/edit-page/<int:band_id>/', views.account_band_edit_page, name='band_edit_page'),
    path('account/admins/<int:band_id>/', views.account_band_admins_page, name='band_admin_page'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('create/user/', views.user_create_news, name='user_create_news'),
    path('create/band/<int:band_id>/', views.band_create_news, name='band_create_news'),
    path('edit/user/<int:news_id>/', views.user_edit_news, name='user_edit_news'),
    path('edit/band/<int:band_id>/<int:news_id>/', views.band_edit_news, name='band_edit_news'),
    path('display/<int:news_id>/', views.news_display_page, name='news_display'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('band/', include('bands.urls', namespace='bands')),
    path('news/', include('news.urls', namespace='news')),
    path('contact/', include('contact_us.urls', namespace='contact')),
    # path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/forms.py
from django import forms
import requests

from .models import News


class CreateNews(forms.ModelForm):
    title = forms.CharField(required=False, label='Naslov',
                            widget=forms.TextInput(
                                attrs={
                                    "class": "form-cotrol",
                                    "title": "Naslov objave ili događaja.",
                                    "placeholder": "Naslov objave ili događaja"
                                }
                            ))
    yt_video = forms.CharField(required=False, label='YouTube link',
                               widget=forms.TextInput(
                                   attrs={
                                       "class": "form-cotrol",
                                       "title": "YouTube link objave ili događaja.",
                                       "placeholder": "YouTube link"
                                   }
                               ))
    fb_event = forms.CharField(required=False, label='Facebook događaj',
                               widget=forms.TextInput(
                                   attrs={
                                       "class": "form-cotrol",
                                       "title": "Facebook link objave ili događaja.",
                                       "placeholder": "Facebook događaj"
                                   }
                               ))

    class Meta:
        model = News
        fields = ['title', 'news', 'news_picture', 'yt_video', 'fb_event']

    def clean_yt_video(self, *args, **kwargs):
        yt_video_raw = self.cleaned_data.get('yt_video')

        video = "https://www.youtube.com/watch?v="
        video_verify = "https://www.youtube.com/embed/"

        if yt_video_raw:
            try:
                response = requests.get(yt_video_raw)
                yt_video = response.url
                yt_video = yt_video.replace("&feature=youtu.be", "")

                if yt_video:
                    if video_verify in yt_video:
                        return yt_video
                    elif video not in yt_video:
                        yt_video = None
                        return yt_video
                    else:
                        yt_video = yt_video.replace("https://www.youtube.com/watch?v=",
                                                    "https://www.youtube.com/embed/")
                        return yt_video
            except:
                raise forms.ValidationError('Niste uneli ispravan YouTube link.')

    def clean_fb_event(self, *args, **kwargs):
        fb_event = self.cleaned_data.get('fb_event')

        face = "https://www.facebook.com/"

        if fb_event:
            if face in fb_event:
                return fb_event
            else:
                raise forms.ValidationError('Niste uneli ispravan Facebook link.')

    def clean(self, *args, **kwargs):
        news_title = self.cleaned_data.get('title')
        news_text = self.cleaned_data.get('news')
        news_picture = self.cleaned_data.get('news_picture')
        yt_video = self.cleaned_data.get('yt_video')
        fb_event = self.cleaned_data.get('fb_event')

        if news_title == '' and news_text == '' and news_picture is None and yt_video is None and fb_event is None:
            raise forms.ValidationError("Ne možete odjaviti vest bez bar jednog unetog podatka.")


class NewsPictureForm(forms.ModelForm):

    class Meta:
        model = News
        fields = ['news_picture']

news/views.py
import os
from django.shortcuts import render, redirect
from django.contrib.auth.views import login_required
from django.contrib.auth import logout
from django.template.loader import render_to_string
from django.http import JsonResponse

from .models import News, Comment
from account.models import Profile
from bands.models import Band

from .forms import CreateNews, NewsPictureForm


@login_required(login_url='/account/login/')
def user_create_news(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    form = CreateNews(request.POST or None)

    # Collecting all user pages
    user_pages = []
    bands = Band.objects.all()
    if bands:
        for b in bands:
            if user == b.creator or user in b.admins.all():
                user_pages.append(b)

    # Checking friend requests
    friend_requests = []
    all_users = Profile.objects.all()
    for u in all_users:
        if user in u.friends.all():
            if u.user in profile.friends.all():
                pass
            else:
                friend_requests.append(u.user)
        else:
            pass

    # Checking logout form
    if 'logout' in request.POST:
        logout(request)
        return redirect("/")

    # Checking search field form in navbar
    if 'site_search' in request.POST:
        name = request.POST['site_search']
        if name == '':
            name = 'all'
        return redirect("/account/search/" + str(name), name)

    if request.method == 'POST' or None:
        form = CreateNews(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            news = form.cleaned_data['news']
            news_picture = form.cleaned_data['news_picture']
            yt_video = form.cleaned_data['yt_video']
            fb_event = form.cleaned_data['fb_event']

            n = News(creator=user, title=title, news=news, news_picture=news_picture,
                     yt_video=yt_video, fb_event=fb_event)

            os.listdir()

            if n.news_picture:
                n.create_news_picture()
            n.save()

            # RENAMING AND UPDATING PATH FOR NEWS PICTURE
            if news_picture:
                os.rename('media/news_picture/' + str(n.creator.id) +
                          '/None/', 'media/news_picture/' + str(n.creator.id) + '/' + str(n.id) + '/')

                News.objects.filter(id=n.id).update(news_picture='news_picture/' + str(n.creator.id) + '/' + str(n.id) + '/' + str(news_picture))

            return redirect("/account/home/")

    content = {
        "account": "account",
        "user_create_news": "user_create_news",
        "title": 'Nova objava',
        "user": user,
        "profile": profile,
        "user_pages": user_pages,
        "form": form,
        "friend_requests": friend_requests,
    }
    return render(request, "news/create_news.html", content)


@login_required(login_url='/account/login/')
def band_create_news(request, band_id):
    user = request.user
    profile = Profile.objects.get(user=user)
    band = Band.objects.get(id=band_id)

    form = CreateNews()

    # Collecting all user pages
    user_pages = []
    bands = Band.objects.all()
    if bands:
        for b in bands:
            if user == b.creator or user in b.admins.all():
                user_pages.append(b)

    # Checking friend requests
    friend_requests = []
    all_users = Profile.objects.all()
    for u in all_users:
        if user in u.friends.all():
            if u.user in profile.friends.all():
                pass
            else:
                friend_requests.append(u.user)
        else:
            pass

    # Checking logout form
    if 'logout' in request.POST:
        logout(request)
        return redirect("/")

    # Checking search field form in navbar
    if 'site_search' in request.POST:
        name = request.POST['site_search']
        if name == '':
            name = 'all'
        return redirect("/account/search/" + str(name), name)

    if request.method == 'POST' or None:
        form = CreateNews(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            news = form.cleaned_data['news']
            news_picture = form.cleaned_data['news_picture']
            yt_video = form.cleaned_data['yt_video']
            fb_event = form.cleaned_data['fb_event']

            n = News(creator=user, band=band, title=title, news=news, news_picture=news_picture,
                     yt_video=yt_video, fb_event=fb_event)

            os.listdir()

            if n.news_picture:
                n.create_news_picture()
            n.save()

            # RENAMING AND UPDATING PATH FOR NEWS PICTURE
            if news_picture:
                os.rename('media/news_picture/' + str(n.creator.id) +
                          '/None/', 'media/news_picture/' + str(n.creator.id) + '/' + str(n.id) + '/')

                News.objects.filter(id=n.id).update(news_picture='news_picture/' + str(n.creator.id) + '/' + str(n.id) + '/' + str(news_picture))

            return redirect("/account/home/")

    content = {
        "account": "account",
        "band_create_news": "band_create_news",
        "band": band,
        "title": 'Nova vest | bend',
        "user": user,
        "profile": profile,
        "user_pages": user_pages,
        "form": form,
        "friend_requests": friend_requests,
    }
    return render(request, "news/create_news.html", content)


@login_required(login_url='/account/login/')
def news_display_page(request, news_id):
    user = request.user
    profile = Profile.objects.get(user=user)
    news = News.objects.get(id=news_id)

    # Collecting comments
    comments = Comment.objects.filter(news=news).order_by('-created')

    # Collecting all user pages
    user_pages = []
    bands = Band.objects.all()
    if bands:
        for b in bands:
            if user == b.creator or user in b.admins.all():
                user_pages.append(b)

    # Checking friend requests
    friend_requests = []
    all_users = Profile.objects.all()
    for u in all_users:
        if user in u.friends.all():
            if u.user in profile.friends.all():
                pass
            else:
                friend_requests.append(u.user)
        else:
            pass

    # Checking logout form
    if 'logout' in request.POST:
        logout(request)
        return redirect("/")

    # Checking search field form in navbar
    if 'site_search' in request.POST:
        name = request.POST['site_search']
        if name == '':
            name = 'all'
        return redirect("/account/search/" + str(name), name)

    # Deleting news
    if 'delete_news' in request.POST:
        instance = News.objects.get(id=news_id)
        instance.delete_picture()
        instance.delete()
        return redirect("/account/home/")

    # AJAX form
    if request.is_ajax():
        user = request.user
        if 'create_comment' in request.POST:
            text = request.POST['text']

            Comment.objects.create(news=news, user=user, text=text)

        elif 'delete_comment' in request.POST:
            comment_id = request.POST['comment_id']
            instance = Comment.objects.filter(id=comment_id)
            instance.delete()

        elif 'update_comment' in request.POST:
            comment_id = request.POST['comment_id']
            text = request.POST['text']
            Comment.objects.filter(id=comment_id).update(text=text)

        # Collecting comments
        comments = Comment.objects.filter(news=news).order_by('-created')

        content = {
            "account": "account",
            "user": user,
            "news_data": news,
            "news_comments": comments,
        }
        html = render_to_string("news/news_comments_ajax.html", content, request=request)
        return JsonResponse({'form': html})

    content = {
        "account": "account",
        "news_display": "news_display",
        "title": "Prikaz vesti",
        "user": user,
        "profile": profile,
        "user_pages": user_pages,
        "news_data": news,
        "news_comments": comments,
        "friend_requests": friend_requests,
    }
    return render(request, "news/news_page.html", content)


@login_required(login_url='/account/login/')
def user_edit_news(request, news_id):
    user = request.user
    profile = Profile.objects.get(user=user)
    news = News.objects.get(id=news_id)

    form = CreateNews(request.POST or None, instance=news)
    form_picture = NewsPictureForm(request.POST or None, instance=news)

    # Collecting all user pages
    user_pages = []
    bands = Band.objects.all()
    if bands:
        for b in bands:
            if user == b.creator or user in b.admins.all():
                user_pages.append(b)

    # Checking friend requests
    friend_requests = []
    all_users = Profile.objects.all()
    for u in all_users:
        if user in u.friends.all():
            if u.user in profile.friends.all():
                pass
            else:
                friend_requests.append(u.user)
        else:
            pass

    # Checking logout form
    if 'logout' in request.POST:
        logout(request)
        return redirect("/")

    # Checking search field form in navbar
    if 'site_search' in request.POST:
        name = request.POST['site_search']
        if name == '':
            name = 'all'
        return redirect("/account/search/" + str(name), name)

    if 'brisi_sliku' in request.POST:
        form_picture = NewsPictureForm(request.POST, request.FILES, instance=news)
        news.delete_picture()

    if 'news_create' in request.POST:
        form = CreateNews(request.POST, instance=news)
        form_picture = NewsPictureForm(request.POST, request.FILES, instance=news)
        if 'news_picture' in request.FILES:
            news.delete_picture()
        if form_picture.is_valid():
            form_picture.save()

news/templates/news/news.html
{% load thumbnail %}

<div class="news">
    <div class="row">
        <div class="{% if news.news_picture or news.yt_video %}col-lg-7{% else %}col-lg-12{% endif %}">
            <div style="display:flex;">
                {% if news.band %}
                <a href="{% url 'bands:account_band_page' news.band.id %}">
                    {% if news.band.logo %}
                    <img class="avatar-like" src="{% thumbnail news.band.logo 200x0 %}">
                    {% else %}
                    <h6><i class="fas fa-guitar fa-2x"></i></h6>
                    {% endif %}
                </a>
                <div>
                    <a href="{% url 'bands:account_band_page' news.band.id %}">
                        <h6 class="news-name">{{ news.band.name }}</h6>
                    </a>
                    <small class="news-date">{{ news.updated|date:"d" }}.{{ news.updated|date:"m" }}.{{ news.updated|date:"Y" }}.</small>
                </div>
                {% else %}
                <a href="{% url 'account:account_profile' news.creator.id %}">
                    {% if news.creator.profile.picture %}
                    <img class="avatar-like" src="{% thumbnail news.creator.profile.picture 150x0 %}">
                    {% else %}
                    <h6><i class="fas fa-user-circle fa-2x"></i></h6>
                    {% endif %}
                </a>
                <div>
                    <a href="{% url 'account:account_profile' news.creator.id %}">
                        <h6 class="news-name">{{ news.creator.first_name }} {{ news.creator.last_name }}</h6>
                    </a>
                    <small class="news-date">{{ news.updated|date:"d" }}.{{ news.updated|date:"m" }}.{{ news.updated|date:"Y" }}.</small>
                </div>
                {% endif %}
            </div>
            {% if news.title %}
            <h6 class="news-title">{{ news.title }}</h6>
            {% endif %}
            <div class="text-justify" style="font-size:14px;">{{ news.news|safe|truncatewords:40|linebreaks }}</div>
            <br>
            <a href="{% url 'news:news_display' news.id %}">Vidi još ...</a>
        </div>
        <div class="{% if news.news_picture or news.yt_video %}col-lg-5{% else %}col-lg-0{% endif %} text-center">
            {% if news.news_picture %}
                <div class="row align-items-center h-100">
                    <div class="col-12 mx-auto">
                        <img id="news_image" src="{% thumbnail news.news_picture 480x0 %}"
                             class="img-fluid"
                             style="height:230px; width:100%; object-fit:cover; margin-bottom:5px; border:2px solid grey;">
                    </div>
                </div>
            {% elif news.yt_video %}
                <div class="row align-items-center h-100">
                    <div class="col-12 mx-auto">
                        <iframe width="100%" height="230" src="{{ news.yt_video }}"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen>
                        </iframe>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

news/templates/news/news_comments_ajax.html
{% load thumbnail %}

{% if news_comments %}
{% for comment in news_comments %}
<div class="comment frame">
    <div style="display: flex;">
        <a href="{% url 'account:account_profile' comment.user.id %}">
            {% if comment.user.profile.picture %}
            <img class="avatar-like" src="{% thumbnail comment.user.profile.picture 150x0 %}">
            {% else %}
            <h6><i class="fas fa-user-circle fa-2x"></i></h6>
            {% endif %}
        </a>
        <div>
            <a href="{% url 'account:account_profile' comment.user.id %}">
                <h6 class="news-name">{{ comment.user.first_name }} {{ comment.user.last_name }}</h6>
            </a>
            <small class="news-date">{{ comment.created|date:"d" }}.{{ comment.created|date:"m" }}.{{ comment.created|date:"Y" }}.</small>
        </div>
    </div>
    {{ comment.text|safe }}
    {% if comment.user == user %}
    <!-- Modals for comments -->
    <div class="modal fade" id="update_comment_modal{{ comment.id }}">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content frame">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h5 class="modal-title"><i class="fas fa-pencil-alt"></i>&nbsp;&nbsp;Uredi Komentar</h5>
                </div>

                <!-- Modal body -->
                <form method="post" action="." name="update_user_comment"> {% csrf_token %}
                    <div class="modal-body">
                        <div id="comment_text">
                            <div class="comment-text-field frame" id="mytextarea{{ comment.id }}" contentEditable="true">
                                {{ comment.text|safe }}
                            </div>
                            <div class="emojis">
                                <span id="heartbroken{{ comment.id }}">&#128148</span>
                                <span id="shit{{ comment.id }}">&#128169</span>
                                <span id="lol{{ comment.id }}">&#128514</span>
                                <span id="wink{{ comment.id }}">&#128521</span>
                                <span id="love{{ comment.id }}">&#128525</span>
                                <span id="angry{{ comment.id }}">&#128545</span>
                                <span id="sad{{ comment.id }}">&#128557</span>
                                <span id="smile{{ comment.id }}">&#128578</span>
                                <span id="think{{ comment.id }}">&#129300</span>
                                <span id="horns{{ comment.id }}">&#129304</span>
                                <span id="like{{ comment.id }}">&#128077</span>
                                <span id="dislike{{ comment.id }}">&#128078</span>
                                <span id="applause{{ comment.id }}">&#128079</span>
                                <span id="finger{{ comment.id }}">&#128405</span>
                            </div>
                            <script>
                                $("#heartbroken{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('💔');
                                });
                                $("#shit{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('💩');
                                });
                                $("#lol{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('😂');
                                });
                                $("#wink{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('😉');
                                });
                                $("#love{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('😍');
                                });
                                $("#angry{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('😡');
                                });
                                $("#sad{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('😭');
                                });
                                $("#smile{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('🙂');
                                });
                                $("#think{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('🤔');
                                });
                                $("#horns{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('🤘');
                                });
                                $("#like{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('👍');
                                });
                                $("#dislike{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('👎');
                                });
                                $("#applause{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('👏');
                                });
                                $("#finger{{ comment.id }}").click(function() {
                                    $("#mytextarea{{ comment.id }}").append('🖕');
                                });
                            </script>
                        </div>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <span class="mr-auto">
                            <button type="button"
                                    class="btn"
                                    data-dismiss="modal"
                                    id="no_update">Ne</button>
                        </span>
                        <button type="submit"
                                name="update_comment"
                                class="btn"
                                value="{{ comment.id }}"
                                data-dismiss="modal"
                                id="yes_update_comment{{ comment.id }}">Da</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="delete_comment_modal{{ comment.id }}">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content frame">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h5 class="modal-title"><i class="fas fa-trash"></i>&nbsp;&nbsp;Obriši Komentar</h5>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <p>Da li ste sigurni da želite da obrišete vaš komentar?</p>
                </div>

                <form method="post" action="." name="update_user_comment"> {% csrf_token %}
                <!-- Modal footer -->
                <div class="modal-footer">
                    <span class="mr-auto">
                        <button type="button"
                                class="btn"
                                data-dismiss="modal"
                                id="no_delete">Ne</button>
                    </span>
                    <button type="submit"
                            name="delete_comment"
                            class="btn"
                            value="{{ comment.id }}"
                            data-dismiss="modal"
                            id="yes_delete_comment{{ comment.id }}">Da</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end of modal -->
    <div style="display:flex;">
        <div class="link">
            <a href="#" data-toggle="modal"
               data-target="#update_comment_modal{{ comment.id }}">UREDI KOMENTAR</a>
        </div>&nbsp;&nbsp;|&nbsp;&nbsp;
        <div class="link">
            <a href="#" data-toggle="modal"
               data-target="#delete_comment_modal{{ comment.id }}">OBRIŠI KOMENTAR</a>
        </div>
    </div>
    <!-- Updating news comment -->
    <script type="text/javascript">
        $(document).ready(function(event){

            $(document).on('click', '#yes_update_comment{{ comment.id }}', function(event){

                event.preventDefault();
                var text = $("#mytextarea{{ comment.id }}").text();
                var comment_id = $("#yes_update_comment{{ comment.id }}").val();
                var self = $(this);
                $(".loading-bar").css("display", "block");

                $.ajax({
                    type: 'POST',
                    url: '/news/display/{{ news_data.id }}/',
                    data: {
                        'text': text,
                        'comment_id': comment_id,
                        'update_comment': 'update_comment',
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    success: function(response){
                        $('.comments').html(response['form']);
                        $(".loading-bar").css("display", "none");
                    }
                });
            });
        });
    </script>

    <!-- Deleting news comment -->
    <script type="text/javascript">
        $(document).ready(function(event){

            $(document).on('click', '#yes_delete_comment{{ comment.id }}', function(event){

                event.preventDefault();
                var comment_id = $("#yes_delete_comment{{ comment.id }}").val();
                var self = $(this);
                $(".loading-bar").css("display", "block");

                $.ajax({
                    type: 'POST',
                    url: '/news/display/{{ news_data.id }}/',
                    data: {
                        'delete_comment': 'delete_comment',
                        'comment_id': comment_id,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    success: function(response){
                        $('.comments').html(response['form']);
                        $(".loading-bar").css("display", "none");
                    }
                });
            });
        });
    </script>
    {% endif %}
</div>
{% endfor %}
{% endif %}